"""user suspension

Revision ID: 231a6ece8657
Revises: e040f72f6bbe
Create Date: 2026-01-24 02:23:56.843333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231a6ece8657'
down_revision: Union[str, Sequence[str], None] = 'e040f72f6bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('suspended_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('suspension_reason', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'suspension_reason')
    op.drop_column('users', 'suspended_until')
    # ### end Alembic commands ###
