"""Initial schema

Revision ID: 7f1c51398e80
Revises: 
Create Date: 2026-01-06 03:02:19.266338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1c51398e80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('points', sa.Integer(), server_default='10000', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), server_default='USER', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='0', nullable=False),
    sa.CheckConstraint('CHAR_LENGTH(nickname) >= 2', name='check_nickname_length'),
    sa.CheckConstraint('points >= 0', name='check_points_positive'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('READY', 'OPEN', 'CLOSED', 'SETTLED', 'CANCELLED', name='eventstatus'), server_default='READY', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('CHAR_LENGTH(title) >= 5', name='check_event_title_length'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('point_history',
    sa.Column('history_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bet_id', sa.String(length=36), nullable=True),
    sa.Column('change_amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('BET', 'WIN', 'LOSE', 'REFUND', 'ETC', name='pointreason'), server_default='ETC', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('points_after', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('event_images',
    sa.Column('image_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('event_options',
    sa.Column('option_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('total_bet_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.CheckConstraint('`order` >= 0', name='check_option_order_positive'),
    sa.CheckConstraint('total_bet_amount >= 0', name='check_total_bet_positive'),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('option_id'),
    sa.UniqueConstraint('event_id', 'name', name='uq_event_option_name')
    )
    op.create_table('bets',
    sa.Column('bet_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('option_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'WIN', 'LOSE', 'REFUNDED', name='betstatus'), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='check_bet_amount_positive'),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['event_options.option_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('bet_id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_user_event_bet')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bets')
    op.drop_table('event_options')
    op.drop_table('event_images')
    op.drop_table('point_history')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
