"""user withdrawl

Revision ID: 9a9774779351
Revises: 231a6ece8657
Create Date: 2026-01-30 01:39:50.090143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9774779351'
down_revision: Union[str, Sequence[str], None] = '231a6ece8657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_withdrawal',
    sa.Column('withdrawal_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('hashed_email', sa.String(length=255), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('withdrawal_id')
    )
    op.create_index(op.f('ix_user_withdrawal_hashed_email'), 'user_withdrawal', ['hashed_email'], unique=False)
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_index(op.f('ix_user_withdrawal_hashed_email'), table_name='user_withdrawal')
    op.drop_table('user_withdrawal')
    # ### end Alembic commands ###
