"""add last_login_at

Revision ID: 9aea6cf592ab
Revises: dbe472ec4ba1
Create Date: 2026-02-06 15:48:48.508002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9aea6cf592ab'
down_revision: Union[str, Sequence[str], None] = 'dbe472ec4ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. nullable=True 상태로 컬럼을 추가
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))

    # 2. 기존 데이터들에 대해 last_login_at 값을 created_at 값으로 복사
    op.execute(sa.text("UPDATE users SET last_login_at = created_at"))

    # 3 nullable=False로 제약 조건을 변경
    op.alter_column('users', 'last_login_at',
               existing_type=sa.DateTime(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_login_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
