"""add social and verify columns to user

Revision ID: a0a00144f8aa
Revises: e2f291088327
Create Date: 2026-01-09 18:02:09.857040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a0a00144f8aa'
down_revision: Union[str, Sequence[str], None] = 'e2f291088327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_snu_verified', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('social_type', sa.Enum('LOCAL', 'GOOGLE', 'KAKAO', name='socialtype'), server_default='LOCAL', nullable=False))
    op.add_column('users', sa.Column('social_id', sa.String(length=200), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['social_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'social_id')
    op.drop_column('users', 'social_type')
    op.drop_column('users', 'is_snu_verified')
    # ### end Alembic commands ###
