"""fix social_id uniqueness in user

Revision ID: c42f66a58a2f
Revises: a0a00144f8aa
Create Date: 2026-01-09 18:10:21.352681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c42f66a58a2f'
down_revision: Union[str, Sequence[str], None] = 'a0a00144f8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('social_id'), table_name='users')
    op.create_unique_constraint('uq_social_type_id', 'users', ['social_type', 'social_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_social_type_id', 'users', type_='unique')
    op.create_index(op.f('social_id'), 'users', ['social_id'], unique=True)
    # ### end Alembic commands ###
