"""increase_comment_length_to_2000

Revision ID: dbe472ec4ba1
Revises: 36bce5369143
Create Date: 2026-02-06 01:04:55.185942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dbe472ec4ba1'
down_revision: Union[str, Sequence[str], None] = '36bce5369143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop old CHECK constraint
    op.drop_constraint('ck_comment_content_length', 'comments', type_='check')
    
    # Add new CHECK constraint with 2000 character limit
    op.create_check_constraint(
        'ck_comment_content_length_v2',
        'comments',
        'LENGTH(content) >= 1 AND LENGTH(content) <= 2000'
    )
    
    op.alter_column('point_history', 'reason',
               existing_type=mysql.ENUM('BET', 'WIN', 'LOSE', 'REFUND', 'ETC', 'SIGNUP', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('SIGNUP', 'BET', 'WIN', 'LOSE', 'REFUND', 'ETC', name='pointreason'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop new CHECK constraint
    op.drop_constraint('ck_comment_content_length_v2', 'comments', type_='check')
    
    # Restore old CHECK constraint with 500 character limit
    op.create_check_constraint(
        'ck_comment_content_length',
        'comments',
        'LENGTH(content) >= 1 AND LENGTH(content) <= 500'
    )
    
    op.alter_column('point_history', 'reason',
               existing_type=sa.Enum('SIGNUP', 'BET', 'WIN', 'LOSE', 'REFUND', 'ETC', name='pointreason'),
               type_=mysql.ENUM('BET', 'WIN', 'LOSE', 'REFUND', 'ETC', 'SIGNUP', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    # ### end Alembic commands ###
