"""add participant_count and option_image_url to event_options

Revision ID: e040f72f6bbe
Revises: c42f66a58a2f
Create Date: 2026-01-15 02:00:49.921223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e040f72f6bbe'
down_revision: Union[str, Sequence[str], None] = 'c42f66a58a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_options', sa.Column('participant_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('event_options', sa.Column('option_total_amount', sa.Integer(), server_default='0', nullable=False))
    op.add_column('event_options', sa.Column('option_image_url', sa.String(length=2048), nullable=True))
    op.drop_column('event_options', 'total_bet_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_options', sa.Column('total_bet_amount', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.drop_column('event_options', 'option_image_url')
    op.drop_column('event_options', 'option_total_amount')
    op.drop_column('event_options', 'participant_count')
    # ### end Alembic commands ###
