"""Add constraints and relationships

Revision ID: e2f291088327
Revises: 7f1c51398e80
Create Date: 2026-01-08 19:01:59.227258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f291088327'
down_revision: Union[str, Sequence[str], None] = '7f1c51398e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint("check_event_start_after_created", "events", "start_at >= created_at")
    op.create_check_constraint("check_event_end_after_start", "events", "end_at > start_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_event_start_after_created", "events", type_="check")
    op.drop_constraint("check_event_end_after_start", "events", type_="check")
    # ### end Alembic commands ###
